SELECT
	JLE.ENTRY_ID,
	JLE.DATE ,
	JLE.ACCOUNT,
	JLE.COST_CENTER,
	JLE.AMOUNT,
	JLE.AMOUNT * FXR.RATE_TO_EUR AS AMOUNT_EUR,
	ENT.ID AS ENTITY_ID,
	JLE.BOOKING_TOOL,
	SOURCE_SYSTEM,
	STATUS,
FROM {{ source('SMMOIDEEN','JOURNAL_ENTRIES') }} JLE
LEFT JOIN {{ ref('ANALYTICS_DIM_ENTITY') }} ENT 
	ON JLE.ENTITY = ENT.ENTITY
LEFT JOIN {{ ref('ANALYTICS_DIM_FX_RATES_ECB') }} FXR 
	ON JLE.CURRENCY = FXR.CURRENCY
	AND JLE.DATE = FXR.DATE