SELECT
	ENTRY_ID,
	DATE ,
	ACCOUNT,
	COST_CENTER,
	AMOUNT,
	AMOUNT * FXR.RATE_TO_EUR AS AMOUNT_EUR,
	JLE.ID AS ENTITY_ID,
	BOOKING_TOOL,
	SOURCE_SYSTEM,
	STATUS,
FROM {{ source('SMMOIDEEN','JOURNAL_ENTRIES') }} JLE
LEFT JOIN {{ ref('ANALYTICS_DIM_ENTITY') }} ENT 
	ON JLE.ENTITY = ENT.ENTITY
LEFT JOIN {{ ref('ANALYTICS_DIM_FX_RATES_ECB') }} FXR 
	ON JLE.CURRENCY = FXR.CURRENCY
	AND JLE.DATE = FXR.DATE