WITH ENTITY_DATA AS
(
	SELECT
		ENTITY,
		CURRENCY
	FROM {{ source('SMMOIDEEN','MANUAL_REPORT_REGISTRY') }}
	UNION ALL
	SELECT
		ENTITY,
		CURRENCY
	FROM {{ source('SMMOIDEEN','JOURNAL_ENTRIES') }}
)
SELECT 
	ROW_NUMBER() OVER (ORDER BY ENTITY, CURRENCY) AS ID,
	ENTITY,
	CURRENCY
FROM ENTITY_DATA;