SELECT
	MRR.REPORT_ID,
	ENT.ID AS ENTITY_ID,
	MRR.DEPARTMENT,
	MRR.PURPOSE,
	MRR.SOURCE_SYSTEMS_USED,
	MRR.AVG_PREPARATION_HOURS,
	MRR.HOURLY_RATE_LOCAL,
	MRR.TOTAL_COST_LOCAL,
	MRR.HOURLY_RATE_LOCAL * FXR.RATE_TO_EUR AS HOURLY_RATE_EUR,
	MRR.TOTAL_COST_LOCAL  * FXR.RATE_TO_EUR AS TOTAL_COST_EUR,	
	MRR.REQUEST_FREQUENCY,
	MRR.AUDIENCE
FROM {{ source('SMMOIDEEN','MANUAL_REPORT_REGISTRY') }} MRR
LEFT JOIN {{ ref('ANALYTICS_DIM_ENTITY') }} ENT 
	ON MRR.ENTITY = ENT.ENTITY
LEFT JOIN {{ ref('ANALYTICS_DIM_FX_RATES_ECB') }} FXR 
	ON MRR.CURRENCY = FXR.CURRENCY 
	AND FXR.DATE = (SELECT MAX(DATE) FROM {{ ref('ANALYTICS_DIM_FX_RATES_ECB') }})