SELECT
	JLE.ENTRY_ID,
	JLE.DATE ,
	JLE.ACCOUNT,
	JLE.COST_CENTER,
	AMOUNT_EUR,
	ENT.COUNTRY AS COUNTRY,
	JLE.BOOKING_TOOL,
	JLE.SOURCE_SYSTEM,
	JLE.STATUS,
	TLM.BOOKING_TOOL_PRIMARY_USE AS BOOKING_TOOL_PRIMARY_USE,
	TLM.DEPARTMENT AS BOOKING_TOOL_DEPARTMENT,
	TLM.MANUAL_STEP_INVOLVED AS BOOKING_TOOL_MANUAL_STEP_INVOLVED,
	TLM.INTEGRATION_WITH_ERP AS BOOKING_TOOL_INTEGRATION_WITH_ERP,
	TLM.LEGACY_FLAG AS BOOKING_TOOL_LEGACY_FLAG,
FROM {{ ref('ANALYTICS_FACT_JOURNAL_ENTRIES') }} JLE
LEFT JOIN {{ ref('ANALYTICS_DIM_ENTITY') }} ENT 
	ON JLE.ENTITY_ID = ENT.ID
LEFT JOIN {{ ref('ANALYTICS_DIM_TOOL_MAPPING') }} TLM 
	on JLE.BOOKING_TOOL = TLM.TOOL_MAPPING