SELECT
	JLE.ENTRY_ID,
	JLE.DATE ,
	JLE.ACCOUNT,
	JLE.COST_CENTER,
	AMOUNT_EUR,
	ENT.COUNTRY AS COUNTRY,
	JLE.BOOKING_TOOL,
	JLE.SOURCE_SYSTEM,
	JLE.STATUS,
FROM {{ ref('ANALYTICS_FACT_JOURNAL_ENTRIES') }} JLE
LEFT JOIN {{ ref('ANALYTICS_DIM_ENTITY') }} ENT 
	ON JLE.ENTITY_ID = ENT.ID