SELECT
	MRR.REPORT_ID,
	ENT.COUNTRY,
	MRR.DEPARTMENT,
	MRR.PURPOSE,
	MRR.SOURCE_SYSTEMS_USED,
	MRR.AVG_PREPARATION_HOURS,
	MRR.HOURLY_RATE_EUR,
	MRR.TOTAL_COST_EUR,	
	MRR.REQUEST_FREQUENCY,
	MRR.YEARLY_REQUEST_COUNT,
	MRR.AUDIENCE,
	TLM.PRIMARY_USE AS BOOKING_TOOL_PRIMARY_USE,
	TLM.DEPARTMENT AS BOOKING_TOOL_DEPARTMENT,
	TLM.MANUAL_STEP_INVOLVED AS BOOKING_TOOL_MANUAL_STEP_INVOLVED,
	TLM.INTEGRATION_WITH_ERP AS BOOKING_TOOL_INTEGRATION_WITH_ERP,
	TLM.LEGACY_FLAG AS BOOKING_TOOL_LEGACY_FLAG,
FROM {{ ref('ANALYTICS_FACT_MANUAL_REPORT_REGISTRY') }} MRR
LEFT JOIN {{ ref('ANALYTICS_DIM_ENTITY') }} ENT 
	ON MRR.ENTITY_ID = ENT.ID
LEFT JOIN {{ ref('ANALYTICS_DIM_TOOL_MAPPING') }} TLM 
	on MRR.SOURCE_SYSTEMS_USED = TLM.TOOL_NAME
