SELECT
	MRR.REPORT_ID,
	ENT.COUNTRY,
	MRR.DEPARTMENT,
	MRR.PURPOSE,
	MRR.SOURCE_SYSTEMS_USED,
	MRR.AVG_PREPARATION_HOURS,
	MRR.HOURLY_RATE_EUR,
	MRR.TOTAL_COST_EUR,	
	MRR.REQUEST_FREQUENCY,
	MRR.AUDIENCE
FROM {{ ref('ANALYTICS_FACT_MANUAL_REPORT_REGISTRY') }} MRR
LEFT JOIN {{ ref('ANALYTICS_DIM_ENTITY') }} ENT 
	ON MRR.ENTITY_ID = ENT.ID
